project:
  type: website
  resources:
    - CNAME

website:
  site-url: https://www.jtrive.com
  title: "The Pleasure of Finding Things Out: A blog by James Triveri"
  description: A technical blog by James Triveri"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jtrive84/
      - icon: linkedin
        href: https://www.linkedin.com/in/jamestriveri/
      - icon: rss
        href: index.xml
      - icon: p-square
        href: https://python-bloggers.com/
format:
  html:
    theme: flatly
    css: styles.css
    highlight-style: dracula
