project:
  type: website

website:
  title: "The Pleasure of Finding Things Out: A blog by James Triveri"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jtrive84/
      - icon: linkedin
        href: https://www.linkedin.com/in/jamestriveri/
format:
  html:
    theme: cerulean
    css: styles.css
    highlight-style: dracula
