<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-08-25">
<meta name="description" content="Parameter efficient fine-tuning of DistilBERT on tornado severity classification task using NOAA event narratives.">

<title>Practical NLP for Risk Modeling, Part IV - Parameter Efficient Fine-tuning with Low-rank Adaptation – The Pleasure of Finding Things Out: A blog by James Triveri</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">The Pleasure of Finding Things Out: A blog by James Triveri</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/jtrive84/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/jamestriveri/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Practical NLP for Risk Modeling, Part IV - Parameter Efficient Fine-tuning with Low-rank Adaptation</h1>
                  <div>
        <div class="description">
          Parameter efficient fine-tuning of DistilBERT on tornado severity classification task using NOAA event narratives.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Python</div>
                <div class="quarto-category">Transformers</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">August 25, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>In <a href="https://www.jtrive.com/posts/practical-nlp-for-risk-modeling-part-2/practical-nlp-for-risk-modeling-part-2.html">Part II</a> of the <em>Practical NLP for Risk Modeling</em> series, we fine-tuned DistilBERT end-to-end on NOAA tornado event narratives. Instead of treating DistilBERT as a fixed feature extractor, every parameter in the model was allowed to update during training. The result was a considerable improvement over the frozen-embedding approach from Part I. But the improvement came at the cost of updating and storing an entire copy of the model for a single downstream task. For DistilBERT this isn’t terribly burdensome. The model has roughly 67 million parameters which is small by modern transformer standards. But the same training approach becomes increasingly expensive as models get larger. If we wanted separate models for property, casualty, claims triage, and submission classification, full fine-tuning would require maintaining a separate set of model weights for each one.</p>
<p>We’ll revisit the tornado severity classification problem one last time and introduce parameter-efficient fine-tuning (PEFT). Specifically, we’ll use Low-Rank Adaptation (LoRA) through Hugging Face’s <code>peft</code> library. The goal is to determine whether we can obtain performance comparable to full fine-tuning while updating only a small fraction of DistilBERT’s parameters. The base model, dataset, target definition, temporal split, tokenizer, batch sizes, and number of training epochs will all be consistent with Part II. The only major difference will be how the model itself is adapted.</p>
<p><br></p>
<section id="full-fine-tuning-revisited" class="level3">
<h3 class="anchored" data-anchor-id="full-fine-tuning-revisited"><strong>Full Fine-Tuning Revisited</strong></h3>
<p>Recall the setup from Part II: We use NOAA Storm Events records from 2008 through 2025 and retain tornadoes rated EF2 or greater.</p>
<p>Our binary target is:</p>
<ul>
<li><code>CLASS = 0</code>: EF2 tornado.</li>
<li><code>CLASS = 1</code>: EF3, EF4, or EF5 tornado.</li>
</ul>
<p>The model receives only the free-text <code>EVENT_NARRATIVE</code> and attempts to determine whether the event represents an EF2 tornado or a more severe EF3+ event.</p>
<p>Training data consists of observations from 2008 through 2022, while observations from 2023 through 2025 are reserved for validation. Keeping the validation period strictly later than the training data gives us a more realistic approximation of how the model might generalize to unseen event narratives.</p>
<p>With full fine-tuning, gradients flow through both the newly initialized classification head and the pretrained DistilBERT encoder. Every trainable weight can therefore be updated.</p>
<p>If a layer contains a weight matrix</p>
<p><span class="math display">\[
W \in \mathbb{R}^{d \times k},
\]</span></p>
<p>full fine-tuning learns a new version of that entire matrix:</p>
<p><span class="math display">\[
W' = W + \Delta W.
\]</span></p>
<p>The update matrix <span class="math inline">\(\Delta W\)</span> contains the same number of elements as <span class="math inline">\(W\)</span>. If <span class="math inline">\(W\)</span> contains several hundred thousand parameters, several hundred thousand parameters are potentially adjusted.</p>
</section>
<section id="parameter-efficient-fine-tuning" class="level3">
<h3 class="anchored" data-anchor-id="parameter-efficient-fine-tuning"><strong>Parameter-Efficient Fine-Tuning</strong></h3>
<p><a href="https://huggingface.co/blog/peft">Parameter-efficient fine-tuning</a> refers to a family of techniques that adapt a pretrained model without updating all of its original parameters.</p>
<p>The idea is that a pretrained transformer already contains a huge amount of useful information. When adapting that model for a narrow downstream task, it may not be necessary to modify all of that information. We can freeze most or all of the pretrained weights and introduce a much smaller collection of trainable parameters. Low-Rank Adaptation (LoRA) is one of the more popular approaches to doing this.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="lora.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Adapter matrices used in LoRA</figcaption>
</figure>
</div>
<p>LoRA freezes the original pretrained weights and represents the downstream weight update using two smaller low-rank matrices. The original paper showed that these learned low-rank updates could achieve performance comparable to full fine-tuning while simultaneously reducing the number of trainable parameters.</p>
<p>Suppose one of the transformer’s linear layers contains the matrix</p>
<p><span class="math display">\[
W_0 \in \mathbb{R}^{d \times k}.
\]</span></p>
<p>During full fine-tuning, we effectively learn a dense update</p>
<p><span class="math display">\[
\Delta W \in \mathbb{R}^{d \times k},
\]</span></p>
<p>such that</p>
<p><span class="math display">\[
W = W_0 + \Delta W.
\]</span></p>
<p>LoRA makes the assumption that the useful change required for a downstream task may have lower dimensionality than the full weight matrix. Instead of learning every element of <span class="math inline">\(\Delta W\)</span>, LoRA approximates it as the product of two smaller matrices:</p>
<p><span class="math display">\[
\Delta W = BA,
\]</span></p>
<p>where</p>
<p><span class="math display">\[
A \in \mathbb{R}^{r \times k} \\
B \in \mathbb{R}^{d \times r}
\]</span></p>
<p>The rank <span class="math inline">\(r\)</span> is intentionally small (<span class="math inline">\(r \ll \min(d,k)\)</span>). The adapted layer becomes</p>
<p><span class="math display">\[
W = W_0 + BA.
\]</span></p>
<p>The original <span class="math inline">\(W_0\)</span> remains frozen. Only <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are trained. This usually significantly reduces the number of parameters that need to be optimized. For example, suppose <span class="math inline">\(W_0 \in \mathbb{R}^{768 \times 768}\)</span>, which consists of 589,824 parameters. If we use LoRA with rank 8, the two LoRA matrices contain only <span class="math inline">\(8 \times 768 + 768 \times 8\)</span> = 12,288 parameters, which corresponds to only ~2% of the original parameter count. Note that LoRA isn’t replacing the pretrained matrix: The low-rank update is added alongside the pretrained weights at inference time.</p>
<p>For an input vector <span class="math inline">\(x\)</span>, instead of computing</p>
<p>$ h = W_0x, $</p>
<p>the adapted layer computes</p>
<p>$ h = W_0x + BAx. $</p>
<p>where <span class="math inline">\(\alpha\)</span> is a scaling parameter that controls the contribution of the LoRA update.</p>
</section>
<section id="matrix-rank" class="level3">
<h3 class="anchored" data-anchor-id="matrix-rank"><strong>Matrix Rank</strong></h3>
<p>I wanted to briefly clarify the concept of ‘low rank’. It is something that gets waved away in many LoRA tutorials, but is crucial to really understanding the technique. The rank of a matrix is the maximum number of linearly independent row vectors or column vectors it contains. It measures the amount of non-redundant information or the true dimensionality of the space spanned by the matrix. For an <span class="math inline">\(m \times n\)</span> matrix, the maximum possible rank is</p>
<p><span class="math display">\[
\mathrm{rank}(W) \leq \mathrm{min}(m,n).
\]</span></p>
<p>So a <span class="math inline">\(768 \times 768\)</span> weight matrix could have rank as high as 768. But if its rank were actually only 8, all of the information in that matrix could be represented using only eight independent column vectors. That would make it a low-rank matrix. In a low-rank matrix, rows or columns can be recreated as combinations of a much smaller subset of core vectors. Within the context of LoRA, <span class="math inline">\(r\)</span> stands for the rank of the low-rank decomposition.</p>
<p>LoRA doesn’t presume that the pretrained transformer’s weights themselves are low rank. The hypothesis is that the change we need to make to those weights during fine-tuning can often be represented by a much lower-rank matrix. For example, if</p>
<p><span class="math display">\[
\Delta W \in \mathbb{R}^{768 \times 768},
\]</span></p>
<p>Instead of updating the full <span class="math inline">\(768 \times 768\)</span> parameters as in full fine-tuning, LoRA assumes that the update to <span class="math inline">\(\Delta W\)</span> can be approximated as the product of two smaller matrices (in this example, <span class="math inline">\(r = 8\)</span>):</p>
<p><span class="math display">\[
A \in \mathbb{R}^{8 \times 768} \\
B \in \mathbb{R}^{768 \times 8}.
\]</span></p>
<p>When we multiply <span class="math inline">\(BA\)</span>, we get a matrix <span class="math inline">\(\Delta W\)</span> that has the same dimension as <span class="math inline">\(W\)</span>.</p>
<p>W = BA ^{768 }. Replacing 8 with any value less than 768 will result in a low-rank matrix, but typically <span class="math inline">\(r\)</span> is kept relatively small (usually no larger than 64).</p>
<p>The intuition is that adapting DistilBERT to our tornado-classification problem probably does not require modifying hundreds of thousands of weights in every attention matrix. The pretrained model already knows a lot about language. Fine-tuning may only need to nudge the model in a relatively small number of task-specific directions. Perhaps the pretrained model already understands words and phrases like <em>destroyed</em>, <em>major structural damage</em>, <em>debris</em>, <em>roof removed</em>, and <em>injuries</em>. Our task doesn’t require teaching the model English from scratch. It primarily needs to learn which combinations of those representations are useful for distinguishing EF2 from EF3+ tornado narratives. LoRA assumes that this adjustment lives in a relatively small subspace.</p>
<p>The easiest mathematical way to understand why low-rank representations are useful is through the singular value decomposition (SVD). Any matrix <span class="math inline">\(W\)</span> can be decomposed as:</p>
<p><span class="math display">\[
W = U \Sigma V^T
\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(U\)</span> contains a set of orthogonal vectors,</li>
<li><span class="math inline">\(V\)</span> contains another set of orthogonal vectors,</li>
<li><span class="math inline">\(\Sigma\)</span> contains the singular values, which indicate the relative importance of those vector pairs.</li>
</ul>
<p>For a square matrix, the singular values can be written as:</p>
<p><span class="math display">\[
\Sigma =
\begin{bmatrix}
\sigma_1 &amp; 0 &amp; \cdots &amp; 0 \\
0 &amp; \sigma_2 &amp; \cdots &amp; 0 \\
\vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
0 &amp; 0 &amp; \cdots &amp; \sigma_n
\end{bmatrix}
\]</span></p>
<p>with</p>
<p><span class="math display">\[
\sigma_1 \geq \sigma_2 \geq \cdots \geq \sigma_n \geq 0.
\]</span></p>
<p>The larger a singular value is, the more important its associated vectors are in reconstructing the original matrix. If most of the information in <span class="math inline">\(W\)</span> is concentrated in the first few singular values, we can approximate <span class="math inline">\(W\)</span> using only the first <span class="math inline">\(r\)</span> components:</p>
<p><span class="math display">\[
W_r = U_r \Sigma_r V_r^T
\]</span></p>
<p>This is called a rank-r approximation. For example, if <span class="math inline">\(W \in \mathbb{R}^{768 \times 768}\)</span> and we choose <span class="math inline">\(r = 8\)</span>, then</p>
<p><span class="math display">\[\begin{align*}
U_8 &amp;\in \mathbb{R}^{768 \times 8}\\
\Sigma_8 &amp;\in \mathbb{R}^{8 \times 8}\\
V_8^T &amp;\in \mathbb{R}^{8 \times 768}\\
W_8 &amp;= U_8 \Sigma_8 V_8^T,
\end{align*}
\]</span></p>
<p>where <span class="math inline">\(W_8 \in \mathbb{R}^{768 \times 768}\)</span>, but the approximation is built from only eight singular components rather than all 768. This is conceptually what LoRA is doing, but LoRA does not compute the SVD of the desired weight update and then keep the largest eight singular components. The update <span class="math inline">\(\Delta W\)</span> is not known beforehand. LoRA instead imposes the low-rank structure directly and learns <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> through gradient descent.</p>
<p>For an example of how low-rank approximations via SVD can be used in image compression, check out <a href="https://www.jtrive.com/posts/svd-image-compression/svd-image-compression.html">this</a> post.</p>
<p><br></p>
</section>
<section id="experimentation" class="level3">
<h3 class="anchored" data-anchor-id="experimentation"><strong>Experimentation</strong></h3>
<p>The same environment used in parts 2 and 3 is used here:</p>
<pre><code>python -m pip install -r https://gist.githubusercontent.com/jtrive84/e313afbf2def24687e3c3247aa836fe9/raw/f2493005d291920dc1fcfd54274b9dfa42004ebe/requirements.txt --quiet</code></pre>
<p>You’ll also need to make sure the Hugging Face peft library is installed:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode sh code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="ex">$</span> python <span class="at">-m</span> pip install peft</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>We can inspect the layers of our original “distilbert-base-uncased” by printing the model object:</p>
<div id="36a710ca" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> transformers <span class="im">import</span> AutoModelForSequenceClassification</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>model_name <span class="op">=</span> <span class="st">"distilbert-base-uncased"</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>base_model <span class="op">=</span> AutoModelForSequenceClassification.from_pretrained(</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    model_name,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    num_labels<span class="op">=</span><span class="dv">2</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(base_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>c:\Users\jtriv\miniforge3\envs\bert\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 100/100 [00:00&lt;00:00, 880.30it/s, Materializing param=distilbert.transformer.layer.5.sa_layer_norm.weight]   
DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     | 
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED | 
vocab_transform.weight  | UNEXPECTED | 
vocab_projector.bias    | UNEXPECTED | 
vocab_layer_norm.bias   | UNEXPECTED | 
vocab_transform.bias    | UNEXPECTED | 
classifier.weight       | MISSING    | 
pre_classifier.bias     | MISSING    | 
classifier.bias         | MISSING    | 
pre_classifier.weight   | MISSING    | 

Notes:
- UNEXPECTED    :can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING   :those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)</code></pre>
</div>
</div>
<p><br></p>
<p>Within each transformer block there is a self-attention module containing several linear projections:</p>
<pre class="text"><code>q_lin
k_lin
v_lin
out_lin</code></pre>
<p>These correspond to the query, key, value, and output projections used by self-attention. The current Hugging Face DistilBERT implementation defines each of these as a linear transformation from the model’s 768-dimensional representation back into 768 dimensions.</p>
<p>The current PEFT documentation points out that targeting all linear layers can give LoRA substantially more capacity which can enable performance closer to full fine-tuning. PEFT supports this directly in the LoRA configuration with:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>target_modules<span class="op">=</span><span class="st">"all-linear"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>More targeted adaptation is possible (for example, only adapting the query and value projections), but our experiments will use <code>target_modules="all-linear"</code>. peft locates the linear layers inside the existing model, freezes the original weights, and attaches trainable low-rank matrices to those layers.</p>
<p>For detailed instructions on creating the NOAA events dataset, refer to the <a href="https://www.jtrive.com/posts/practical-nlp-for-risk-modeling-part-2/practical-nlp-for-risk-modeling-part-2.html">second post</a> in this series. The pre-processing steps are reproduced in the next cell.</p>
<div id="44f96bf7" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> datasets <span class="im">import</span> Dataset, DatasetDict</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>np.set_printoptions(suppress<span class="op">=</span><span class="va">True</span>, precision<span class="op">=</span><span class="dv">5</span>, linewidth<span class="op">=</span><span class="dv">1000</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>pd.options.mode.chained_assignment <span class="op">=</span> <span class="va">None</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>pd.set_option(<span class="st">"display.max_columns"</span>, <span class="va">None</span>)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>pd.set_option(<span class="st">"display.width"</span>, <span class="va">None</span>)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>pd.set_option(<span class="st">"display.precision"</span>, <span class="dv">5</span>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the NOAA Storm Events database into `dfall` before filtering.</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>dfall <span class="op">=</span> pd.read_parquet(<span class="st">"noaa-events-2008-2025.parquet"</span>)</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> (</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>    dfall[</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>        (dfall.YEAR <span class="op">&gt;=</span> <span class="dv">2008</span>) <span class="op">&amp;</span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>        (dfall.EVENT_TYPE <span class="op">==</span> <span class="st">"Tornado"</span>) <span class="op">&amp;</span></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>        (<span class="op">~</span>dfall.TOR_F_SCALE.isin([<span class="st">"EFU"</span>, <span class="st">"EF0"</span>, <span class="st">"EF1"</span>, <span class="st">"F0"</span>, <span class="st">"F1"</span>]))</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>    .dropna(subset<span class="op">=</span>[<span class="st">"EVENT_NARRATIVE"</span>])</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>    .drop_duplicates(subset<span class="op">=</span>[<span class="st">"EVENT_NARRATIVE"</span>])</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>    .reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"EVENT_NARRATIVE"</span>] <span class="op">=</span> (</span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">"EVENT_NARRATIVE"</span>]</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">str</span>.replace(<span class="vs">r"\s+"</span>, <span class="st">" "</span>, regex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">str</span>.strip()</span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"CLASS"</span>] <span class="op">=</span> np.where(df.TOR_F_SCALE <span class="op">==</span> <span class="st">"EF2"</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a>keep_columns <span class="op">=</span> [</span>
<span id="cb8-39"><a href="#cb8-39" aria-hidden="true" tabindex="-1"></a>    <span class="st">"EVENT_ID"</span>,</span>
<span id="cb8-40"><a href="#cb8-40" aria-hidden="true" tabindex="-1"></a>    <span class="st">"EVENT_NARRATIVE"</span>,</span>
<span id="cb8-41"><a href="#cb8-41" aria-hidden="true" tabindex="-1"></a>    <span class="st">"TOR_F_SCALE"</span>,</span>
<span id="cb8-42"><a href="#cb8-42" aria-hidden="true" tabindex="-1"></a>    <span class="st">"BEGIN_LAT"</span>,</span>
<span id="cb8-43"><a href="#cb8-43" aria-hidden="true" tabindex="-1"></a>    <span class="st">"BEGIN_LON"</span>,</span>
<span id="cb8-44"><a href="#cb8-44" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CLASS"</span></span>
<span id="cb8-45"><a href="#cb8-45" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb8-46"><a href="#cb8-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-47"><a href="#cb8-47" aria-hidden="true" tabindex="-1"></a>dftrain <span class="op">=</span> df[df[<span class="st">"YEAR"</span>] <span class="op">&lt;=</span> <span class="dv">2022</span>][keep_columns].reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb8-48"><a href="#cb8-48" aria-hidden="true" tabindex="-1"></a>dfvalid <span class="op">=</span> df[df[<span class="st">"YEAR"</span>] <span class="op">&gt;</span> <span class="dv">2022</span>][keep_columns].reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb8-49"><a href="#cb8-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-50"><a href="#cb8-50" aria-hidden="true" tabindex="-1"></a>ds_train <span class="op">=</span> Dataset.from_pandas(dftrain)</span>
<span id="cb8-51"><a href="#cb8-51" aria-hidden="true" tabindex="-1"></a>ds_valid <span class="op">=</span> Dataset.from_pandas(dfvalid)</span>
<span id="cb8-52"><a href="#cb8-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-53"><a href="#cb8-53" aria-hidden="true" tabindex="-1"></a>ds <span class="op">=</span> DatasetDict({</span>
<span id="cb8-54"><a href="#cb8-54" aria-hidden="true" tabindex="-1"></a>    <span class="st">"train"</span>: ds_train,</span>
<span id="cb8-55"><a href="#cb8-55" aria-hidden="true" tabindex="-1"></a>    <span class="st">"valid"</span>: ds_valid</span>
<span id="cb8-56"><a href="#cb8-56" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb8-57"><a href="#cb8-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-58"><a href="#cb8-58" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Train size: </span><span class="sc">{</span><span class="bu">len</span>(dftrain)<span class="sc">:,}</span><span class="ss">"</span>)</span>
<span id="cb8-59"><a href="#cb8-59" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Valid size: </span><span class="sc">{</span><span class="bu">len</span>(dfvalid)<span class="sc">:,}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Train size: 2,620
Valid size: 641</code></pre>
</div>
</div>
<p>Tokenization is also unchanged:</p>
<div id="cell-8" class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> time <span class="im">import</span> perf_counter</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> transformers <span class="im">import</span> (</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    AutoTokenizer,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    AutoModel,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    AutoModelForSequenceClassification,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    DataCollatorWithPadding,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    TrainingArguments,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    Trainer</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>tokenizer <span class="op">=</span> AutoTokenizer.from_pretrained(model_name)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> tokenize_batch(batch):</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> tokenizer(</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>        batch[<span class="st">"EVENT_NARRATIVE"</span>],</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>        truncation<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>        max_length<span class="op">=</span><span class="dv">512</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>ds_tokenized <span class="op">=</span> ds.<span class="bu">map</span>(tokenize_batch, batched<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>ds_tokenized <span class="op">=</span> ds_tokenized.remove_columns(</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"EVENT_NARRATIVE"</span>, <span class="st">"TOR_F_SCALE"</span>, <span class="st">"EVENT_ID"</span>, <span class="st">"BEGIN_LAT"</span>, <span class="st">"BEGIN_LON"</span>]</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>ds_tokenized <span class="op">=</span> ds_tokenized.rename_column(<span class="st">"CLASS"</span>, <span class="st">"labels"</span>)</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>ds_tokenized.set_format(<span class="st">"torch"</span>)</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>collator <span class="op">=</span> DataCollatorWithPadding(tokenizer<span class="op">=</span>tokenizer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Map: 100%|██████████| 2620/2620 [00:00&lt;00:00, 7947.37 examples/s]
Map: 100%|██████████| 641/641 [00:00&lt;00:00, 6533.07 examples/s]</code></pre>
</div>
</div>
<p><br></p>
<p>Because the dataset and tokenization pipeline are identical, differences in the two experiments should primarily reflect the adaptation strategy rather than differences in the underlying inputs.</p>
<p>Import the necessary callables from peft and initalize a fresh copy of DistilBERT. We pass the model along with <code>LoraConfig</code> into <code>get_peft_model</code>:</p>
<div id="727bf8a0" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> peft <span class="im">import</span> LoraConfig, TaskType, get_peft_model</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>device <span class="op">=</span> torch.device(<span class="st">"cuda"</span> <span class="cf">if</span> torch.cuda.is_available() <span class="cf">else</span> <span class="st">"cpu"</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> AutoModelForSequenceClassification.from_pretrained(</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    model_name,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    num_labels<span class="op">=</span><span class="dv">2</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>).to(device)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>lora_config <span class="op">=</span> LoraConfig(</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    task_type<span class="op">=</span>TaskType.SEQ_CLS,</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    r<span class="op">=</span><span class="dv">32</span>,</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    lora_alpha<span class="op">=</span><span class="dv">128</span>,</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>    lora_dropout<span class="op">=</span><span class="fl">0.05</span>,</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>    target_modules<span class="op">=</span><span class="st">"all-linear"</span>, <span class="co">#["q_lin", "v_lin"],</span></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>    modules_to_save<span class="op">=</span>[<span class="st">"pre_classifier"</span>, <span class="st">"classifier"</span>],</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>    bias<span class="op">=</span><span class="st">"none"</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>lora_model <span class="op">=</span> get_peft_model(</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>    model,</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>    lora_config</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"device: </span><span class="sc">{</span>device<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading weights: 100%|██████████| 100/100 [00:00&lt;00:00, 783.16it/s, Materializing param=distilbert.transformer.layer.5.sa_layer_norm.weight]   
DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     | 
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED | 
vocab_transform.weight  | UNEXPECTED | 
vocab_projector.bias    | UNEXPECTED | 
vocab_layer_norm.bias   | UNEXPECTED | 
vocab_transform.bias    | UNEXPECTED | 
classifier.weight       | MISSING    | 
pre_classifier.bias     | MISSING    | 
classifier.bias         | MISSING    | 
pre_classifier.weight   | MISSING    | 

Notes:
- UNEXPECTED    :can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING   :those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>device: cpu</code></pre>
</div>
</div>
<p>It’s necessary to create a fresh copy of the model, since <code>get_peft_model</code> modifies the supplied model by attaching adapter modules, so we don’t want to reuse our already fine-tuned model from the previous experiment. Hugging Face specifically notes that PEFT modifies the base model in place.</p>
<p>Best results were realized when <span class="math inline">\(\alpha / r = 4\)</span>. This will vary from application to application, but <span class="math inline">\(r=32\)</span> and <span class="math inline">\(\alpha = 128\)</span> worked best for our dataset.</p>
<p>The <code>LoraConfig</code> arguments are worth calling out:</p>
<ul>
<li><p><code>task_type=TaskType.SEQ_CLS</code>: Tells PEFT that we’re performing sequence classification.</p></li>
<li><p><code>r=32</code>: The rank of the low-rank decomposition.</p></li>
<li><p><code>lora_alpha=128</code>: Controls the scaling applied to the LoRA contribution</p></li>
<li><p><code>lora_dropout=0.05</code>: Applies dropout within the LoRA branch during training and serves as an additional form of regularization.</p></li>
<li><p><code>target_modules="all-linear</code>: Insert LoRA adapters into DistilBERT’s linear layers.</p></li>
<li><p><code>modules_to_save</code>: Allows the classification layers to remain trainable and save them along with the LoRA adapters.</p></li>
</ul>
<p>Hugging Face provides a convenient method to verify that our model has been configured correctly, and to provide us with a count of the number of trainable parameters:</p>
<div id="0d0c1439" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>lora_model.print_trainable_parameters()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>trainable params: 3,246,338 || all params: 70,201,348 || trainable%: 4.6243</code></pre>
</div>
</div>
<p>With this configuration, less than 5% of the model is trainable, which is what we expect. We’re still running the complete DistilBERT model during the forward pass, but we’re optimizing only a small collection of adapter and classification parameters during backpropagation.</p>
<p>We can continue using the ordinary Hugging Face <code>Trainer</code>. PEFT models are designed to work with the standard Transformers training workflow; parameters with <code>requires_grad=False</code> remain frozen while the adapter parameters are optimized. Most of the configuration remains identical to the full fine-tuning experiment. The main change is the learning rate, which we changed from 2e-5 to 1e-4. According to the docs:</p>
<blockquote class="blockquote">
<p>LoRA commonly tolerates and often benefits from a higher learning rate, since we’re optimizing a small set of newly initialized adapter parameters instead of gently modifying every pretrained parameter,</p>
</blockquote>
<p>Everything else remains unchanged.</p>
<div id="3e8dc63d" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> (</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    accuracy_score,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    classification_report,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    roc_auc_score,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    average_precision_score</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> softmax(x):</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> x <span class="op">-</span> x.<span class="bu">max</span>(axis<span class="op">=</span><span class="dv">1</span>, keepdims<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>    exp_x <span class="op">=</span> np.exp(x)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> exp_x <span class="op">/</span> exp_x.<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>, keepdims<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> compute_metrics(eval_pred):</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>    logits, labels <span class="op">=</span> eval_pred</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>    probs <span class="op">=</span> softmax(logits)[:, <span class="dv">1</span>]</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>    preds <span class="op">=</span> (probs <span class="op">&gt;=</span> <span class="fl">0.5</span>).astype(<span class="bu">int</span>)</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>        <span class="st">"accuracy"</span>: accuracy_score(labels, preds),</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>        <span class="st">"roc_auc"</span>: roc_auc_score(labels, probs),</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>        <span class="st">"average_precision"</span>: average_precision_score(labels, probs),</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>lora_args <span class="op">=</span> TrainingArguments(</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>    output_dir<span class="op">=</span><span class="st">"distilbert-noaa-lora"</span>,</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>    eval_strategy<span class="op">=</span><span class="st">"epoch"</span>,</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>    save_strategy<span class="op">=</span><span class="st">"epoch"</span>,</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>    logging_strategy<span class="op">=</span><span class="st">"steps"</span>,</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>    logging_steps<span class="op">=</span><span class="dv">50</span>,</span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a>    learning_rate<span class="op">=</span><span class="fl">1e-4</span>,</span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>    per_device_train_batch_size<span class="op">=</span><span class="dv">8</span>,</span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>    per_device_eval_batch_size<span class="op">=</span><span class="dv">16</span>,</span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>    num_train_epochs<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a>    weight_decay<span class="op">=</span><span class="fl">0.01</span>,</span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>    load_best_model_at_end<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>    metric_for_best_model<span class="op">=</span><span class="st">"roc_auc"</span>,</span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a>    greater_is_better<span class="op">=</span><span class="va">True</span></span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a>lora_trainer <span class="op">=</span> Trainer(</span>
<span id="cb17-41"><a href="#cb17-41" aria-hidden="true" tabindex="-1"></a>    model<span class="op">=</span>lora_model,</span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a>    args<span class="op">=</span>lora_args,</span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a>    train_dataset<span class="op">=</span>ds_tokenized[<span class="st">"train"</span>],</span>
<span id="cb17-44"><a href="#cb17-44" aria-hidden="true" tabindex="-1"></a>    eval_dataset<span class="op">=</span>ds_tokenized[<span class="st">"valid"</span>],</span>
<span id="cb17-45"><a href="#cb17-45" aria-hidden="true" tabindex="-1"></a>    data_collator<span class="op">=</span>collator,</span>
<span id="cb17-46"><a href="#cb17-46" aria-hidden="true" tabindex="-1"></a>    compute_metrics<span class="op">=</span>compute_metrics</span>
<span id="cb17-47"><a href="#cb17-47" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="bece4acd" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>start <span class="op">=</span> perf_counter()</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>lora_trainer.train()</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>lora_train_time <span class="op">=</span> perf_counter() <span class="op">-</span> start</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>lora_metrics <span class="op">=</span> lora_trainer.evaluate()</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"LoRA training time: </span><span class="sc">{</span>lora_train_time <span class="op">/</span> <span class="dv">60</span><span class="sc">:.2f}</span><span class="ss"> minutes"</span>)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(lora_metrics)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">

    <div>
      
      <progress value="1640" max="1640" style="width:300px; height:20px; vertical-align: middle;"></progress>
      [1640/1640 1:17:03, Epoch 5/5]
    </div>
    
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Epoch</th>
<th data-quarto-table-cell-role="th">Training Loss</th>
<th data-quarto-table-cell-role="th">Validation Loss</th>
<th data-quarto-table-cell-role="th">Accuracy</th>
<th data-quarto-table-cell-role="th">Roc Auc</th>
<th data-quarto-table-cell-role="th">Average Precision</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0.518267</td>
<td>0.500690</td>
<td>0.784711</td>
<td>0.753141</td>
<td>0.515328</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.442679</td>
<td>0.441933</td>
<td>0.801872</td>
<td>0.783167</td>
<td>0.571577</td>
</tr>
<tr class="odd">
<td>3</td>
<td>0.321344</td>
<td>0.318293</td>
<td>0.889236</td>
<td>0.924000</td>
<td>0.813039</td>
</tr>
<tr class="even">
<td>4</td>
<td>0.183948</td>
<td>0.360838</td>
<td>0.893916</td>
<td>0.926173</td>
<td>0.810485</td>
</tr>
<tr class="odd">
<td>5</td>
<td>0.228783</td>
<td>0.381376</td>
<td>0.898596</td>
<td>0.925536</td>
<td>0.814564</td>
</tr>
</tbody>
</table>
<p>
</p></div>
<div class="cell-output cell-output-display">

</div>
<div class="cell-output cell-output-stdout">
<pre><code>LoRA training time: 77.09 minutes
{'eval_loss': 0.36083751916885376, 'eval_accuracy': 0.8939157566302652, 'eval_roc_auc': 0.9261726857617267, 'eval_average_precision': 0.8104847707563383, 'eval_runtime': 105.0608, 'eval_samples_per_second': 6.101, 'eval_steps_per_second': 0.39, 'epoch': 5.0}</code></pre>
</div>
</div>
<p>Generating the classification report:</p>
<div id="40479834" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>pred_out <span class="op">=</span> lora_trainer.predict(ds_tokenized[<span class="st">"valid"</span>])</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>logits <span class="op">=</span> pred_out.predictions</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>p1 <span class="op">=</span> softmax(logits)[:, <span class="dv">1</span>] </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>y_valid <span class="op">=</span> pred_out.label_ids</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Assume 0.50 threshold for time being.</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> (p1 <span class="op">&gt;=</span> <span class="fl">0.5</span>).astype(<span class="bu">int</span>)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(classification_report(y_valid, y_pred, digits<span class="op">=</span><span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              precision    recall  f1-score   support

           0    0.92958   0.93333   0.93145       495
           1    0.77083   0.76027   0.76552       146

    accuracy                        0.89392       641
   macro avg    0.85021   0.84680   0.84848       641
weighted avg    0.89342   0.89392   0.89366       641
</code></pre>
</div>
</div>
<p>For comparison, the result from the full fine-tuning experiment:</p>
<pre><code>              precision    recall  f1-score   support

           0    0.94643   0.96364   0.95495       495
           1    0.86861   0.81507   0.84099       146

    accuracy                        0.92980       641
   macro avg    0.90752   0.88935   0.89797       641
weighted avg    0.92870   0.92980   0.92900       641</code></pre>
<p>What stands out is the jump in ROC-AUC and average precision from epoch 2 to 3. ROC-AUC goes from 0.783 to 0.924, and average precision from 0.572 to 0.813. This might reflect the adapter suddenly having enough influence on the frozen model to learn the task effectively.</p>
<p>Initially I was surprised that the LoRA training run took almost as long as the full fine-tuning training run (77 minutes vs.&nbsp;81 minutes on CPU respectively). I assumed since only 5% of model parameters were being updated, this should have been reflected in the runtime. But LoRA is parameter efficient, not necessarily compute efficient. Even though only ~5% of the model parameters were trainable, the complete DistilBERT encoder still has to execute during every forward pass. The attention calculations and feed-forward networks haven’t gone away. The main savings are that gradients and optimizer state for the frozen weights aren’t needed. Hugging Face’s PEFT documentation calls out this distinction: PEFT greatly reduces gradient and optimizer-state memory, while activations and base-model computation remain important costs.</p>
<p>Our results position LoRA as a useful middle ground between frozen embeddings (the approach from <a href="https://www.jtrive.com/posts/practical-nlp-for-risk-modeling-part-1/practical-nlp-for-risk-modeling-part-1.html">Part I in the series</a>) and full fine-tuning. The final LoRA model with <span class="math inline">\(r=32\)</span> and <span class="math inline">\(\alpha=128\)</span>, achieved a ROC-AUC of 0.926 and average precision of 0.810, much stronger than the frozen-embedding approach, though still short of the fully fine-tuned model (0.967 ROC-AUC and 0.912 average precision). That gap is not especially surprising: Full fine-tuning gives the optimizer freedom to update the entire transformer, while LoRA constrains adaptation to a small set of low-rank parameters. The experiments also reinforced that LoRA requires meaningful tuning of its own. Specifically, increasing <code>lora_alpha</code> had a dramatic effect on performance by increasing the influence of the learned low-rank updates relative to the frozen base model. LoRA should not be viewed as a drop-in replacement guaranteed to match full fine-tuning, but as a tradeoff: In this experiment it retained much of the benefit of adapting DistilBERT while training only a small fraction of its parameters. For larger models, or situations where many task-specific versions of the same base model must be maintained, that tradeoff can become considerably more attractive.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/www\.jtrive\.com");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>